GET http://localhost:3000/categories
###

GET http://localhost:3000/categories/1
###

POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Fofocas"
}
###

PATCH http://localhost:3000/categories/4
Content-Type: application/json

{
    "name": "Eventos"
}
###

DELETE http://localhost:3000/categories/3
###

GET http://localhost:3000/posts
###

GET http://localhost:3000/posts/1
###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "titulo": "Babado Novo",    
    "categoryId": 1,
    "userId": 1
}
###

PATCH http://localhost:3000/posts/2
Content-Type: application/json

{
    "titulo": "Post 2"    
}
###

DELETE http://localhost:3000/posts/1

###

GET http://localhost:3000/users
###

GET http://localhost:3000/users/1
###


POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "leandro_rochatolentino@yahoo.com.br",
    "password": "123"    
}
###

PATCH http://localhost:3000/users/2
Content-Type: application/json

{
    "email": "teste@teste.com.br"    
}
###

DELETE http://localhost:3000/users/1